insert into public.jobs (
  canonical_url,
  dedupe_key,
  company,
  role_title,
  department,
  location,
  geography,
  work_mode,
  experience_level,
  salary_min,
  salary_max,
  salary_currency,
  salary_range,
  description_normalized,
  required_skills,
  responsibilities,
  interview_topics,
  quality_score,
  freshness_score,
  is_active
)
values
  (
    'https://jobs.example.com/wipro/entra-id-administrator',
    'wipro-entra-id-administrator-bengaluru',
    'Wipro',
    'Entra ID Administrator',
    'Enterprise Identity',
    'Bengaluru',
    'India',
    'hybrid',
    'mid',
    2200000,
    2900000,
    'INR',
    '22-29 LPA',
    'Administer Entra ID, support MFA and Conditional Access rollouts, and automate access operations with PowerShell.',
    array['Azure AD', 'MFA', 'PowerShell', 'Conditional Access'],
    array['Administer tenant identity services', 'Roll out MFA controls', 'Automate routine access operations'],
    array['Entra ID administration', 'MFA operations', 'Conditional Access'],
    84,
    77,
    true
  ),
  (
    'https://jobs.example.com/ibm/identity-operations-engineer',
    'ibm-identity-operations-engineer-noida',
    'IBM',
    'Identity Operations Engineer',
    'Security Operations',
    'Noida',
    'India',
    'hybrid',
    'mid',
    2000000,
    2800000,
    'INR',
    '20-28 LPA',
    'Run identity operations, manage Azure AD access changes, support access reviews, and script repeatable tasks.',
    array['Azure AD', 'MFA', 'PowerShell', 'Access reviews'],
    array['Support identity operations', 'Coordinate access reviews', 'Script repeatable administration tasks'],
    array['Identity operations', 'Access reviews', 'PowerShell automation'],
    83,
    75,
    true
  ),
  (
    'https://jobs.example.com/capgemini/iam-automation-engineer',
    'capgemini-iam-automation-engineer-chennai',
    'Capgemini',
    'IAM Automation Engineer',
    'Cloud Security',
    'Chennai',
    'India',
    'hybrid',
    'mid',
    2400000,
    3100000,
    'INR',
    '24-31 LPA',
    'Automate identity operations across Azure AD and SaaS systems using PowerShell and Microsoft Graph scripts.',
    array['Azure AD', 'PowerShell', 'Graph API scripting', 'SSO'],
    array['Build automation scripts', 'Support SSO configurations', 'Improve joiner mover leaver workflows'],
    array['PowerShell', 'Graph API', 'SSO'],
    82,
    74,
    true
  ),
  (
    'https://jobs.example.com/hcltech/entra-security-engineer',
    'hcltech-entra-security-engineer-bengaluru',
    'HCLTech',
    'Entra Security Engineer',
    'Identity Security',
    'Bengaluru',
    'India',
    'remote',
    'mid',
    2600000,
    3400000,
    'INR',
    '26-34 LPA',
    'Harden Entra ID with Conditional Access, MFA, and Zero Trust controls while partnering with security engineering teams.',
    array['Azure AD', 'MFA', 'Conditional Access', 'Zero Trust'],
    array['Improve tenant security posture', 'Implement Conditional Access policies', 'Coordinate with security stakeholders'],
    array['Conditional Access', 'Zero Trust', 'Identity security'],
    88,
    79,
    true
  ),
  (
    'https://jobs.example.com/ey/cloud-identity-analyst',
    'ey-cloud-identity-analyst-gurgaon',
    'EY',
    'Cloud Identity Analyst',
    'Cyber Security',
    'Gurgaon',
    'India',
    'hybrid',
    'junior',
    1700000,
    2300000,
    'INR',
    '17-23 LPA',
    'Support Azure AD administration, user provisioning, MFA enablement, and lightweight automation for identity teams.',
    array['Azure AD', 'MFA', 'User provisioning', 'PowerShell'],
    array['Handle user provisioning tasks', 'Support MFA enablement', 'Assist with identity automation'],
    array['Azure AD administration', 'Provisioning', 'PowerShell basics'],
    80,
    72,
    true
  ),
  (
    'https://jobs.example.com/tcs/identity-access-administrator',
    'tcs-identity-access-administrator-mumbai',
    'TCS',
    'Identity and Access Administrator',
    'Managed Services',
    'Mumbai',
    'India',
    'onsite',
    'junior',
    1600000,
    2200000,
    'INR',
    '16-22 LPA',
    'Manage identity access operations, administer Azure AD, enforce MFA, and script support workflows.',
    array['Azure AD', 'MFA', 'Access management', 'PowerShell'],
    array['Administer user access', 'Enforce MFA controls', 'Support ticket-driven access changes'],
    array['Access management', 'MFA', 'PowerShell support scripts'],
    79,
    70,
    true
  ),
  (
    'https://jobs.example.com/kyndryl/identity-automation-specialist',
    'kyndryl-identity-automation-specialist-remote',
    'Kyndryl',
    'Identity Automation Specialist',
    'Platform Engineering',
    'Remote',
    'Global',
    'remote',
    'mid',
    2300000,
    3000000,
    'INR',
    '23-30 LPA',
    'Automate Azure AD identity workflows, MFA operations, and lifecycle controls for enterprise customers.',
    array['Azure AD', 'PowerShell', 'Automation', 'MFA'],
    array['Automate identity workflows', 'Support customer environments', 'Maintain provisioning scripts'],
    array['Automation', 'Azure AD operations', 'Lifecycle management'],
    85,
    76,
    true
  ),
  (
    'https://jobs.example.com/ltimindtree/entra-id-engineer',
    'ltimindtree-entra-id-engineer-hyderabad',
    'LTIMindtree',
    'Entra ID Engineer',
    'Cloud Identity',
    'Hyderabad',
    'India',
    'hybrid',
    'mid',
    2100000,
    2900000,
    'INR',
    '21-29 LPA',
    'Build and support Entra ID operations with Azure AD, MFA, Conditional Access, and PowerShell-driven admin tasks.',
    array['Azure AD', 'Conditional Access', 'MFA', 'PowerShell'],
    array['Support Entra ID operations', 'Implement Conditional Access changes', 'Automate admin workflows'],
    array['Conditional Access', 'PowerShell', 'Identity administration'],
    84,
    74,
    true
  ),
  (
    'https://jobs.example.com/cognizant/identity-support-engineer',
    'cognizant-identity-support-engineer-pune',
    'Cognizant',
    'Identity Support Engineer',
    'Cloud Operations',
    'Pune',
    'India',
    'hybrid',
    'junior',
    1700000,
    2400000,
    'INR',
    '17-24 LPA',
    'Support Azure AD administration, MFA troubleshooting, and PowerShell-assisted user access operations.',
    array['Azure AD', 'MFA', 'PowerShell', 'ServiceNow'],
    array['Troubleshoot identity incidents', 'Handle access requests', 'Maintain support scripts'],
    array['Support troubleshooting', 'MFA', 'PowerShell'],
    81,
    73,
    true
  )
on conflict (canonical_url) do update
set
  dedupe_key = excluded.dedupe_key,
  company = excluded.company,
  role_title = excluded.role_title,
  department = excluded.department,
  location = excluded.location,
  geography = excluded.geography,
  work_mode = excluded.work_mode,
  experience_level = excluded.experience_level,
  salary_min = excluded.salary_min,
  salary_max = excluded.salary_max,
  salary_currency = excluded.salary_currency,
  salary_range = excluded.salary_range,
  description_normalized = excluded.description_normalized,
  required_skills = excluded.required_skills,
  responsibilities = excluded.responsibilities,
  interview_topics = excluded.interview_topics,
  quality_score = excluded.quality_score,
  freshness_score = excluded.freshness_score,
  is_active = excluded.is_active,
  updated_at = now();
