insert into public.jobs (
  canonical_url,
  dedupe_key,
  company,
  role_title,
  department,
  location,
  geography,
  work_mode,
  experience_level,
  salary_min,
  salary_max,
  salary_currency,
  salary_range,
  description_normalized,
  required_skills,
  responsibilities,
  interview_topics,
  quality_score,
  freshness_score,
  is_active
)
values
  (
    'https://jobs.example.com/microsoft/azure-ad-engineer',
    'microsoft-azure-ad-engineer-bengaluru',
    'Microsoft',
    'Azure AD Engineer',
    'Identity Platform',
    'Bengaluru',
    'India',
    'hybrid',
    'mid',
    3000000,
    4000000,
    'INR',
    '30-40 LPA',
    'Own identity platform operations, conditional access policy design, Azure AD Connect health, and PowerShell automation.',
    array['Azure AD', 'Conditional Access', 'Azure AD Connect', 'PowerShell automation', 'Zero Trust'],
    array['Manage tenant security posture', 'Automate identity workflows', 'Troubleshoot sync issues'],
    array['Conditional Access', 'Troubleshooting', 'PowerShell'],
    92,
    88,
    true
  ),
  (
    'https://jobs.example.com/okta/iam-engineer',
    'okta-iam-engineer-remote',
    'Okta',
    'IAM Engineer',
    'Identity Engineering',
    'Remote',
    'Global',
    'remote',
    'mid',
    2800000,
    3600000,
    'INR',
    '28-36 LPA',
    'Deliver identity automation, access reviews, and lifecycle orchestration across SaaS systems.',
    array['IAM', 'Access reviews', 'Workflow automation', 'Okta', 'SSO'],
    array['Build lifecycle workflows', 'Run access certifications', 'Partner with security teams'],
    array['Automation', 'Identity governance', 'Okta administration'],
    89,
    84,
    true
  ),
  (
    'https://jobs.example.com/accenture/cloud-identity-engineer',
    'accenture-cloud-identity-engineer-hyderabad',
    'Accenture',
    'Cloud Identity Engineer',
    'Cloud Security',
    'Hyderabad',
    'India',
    'hybrid',
    'mid',
    2400000,
    3000000,
    'INR',
    '24-30 LPA',
    'Support Entra ID, identity governance, privileged access, and enterprise authentication flows.',
    array['Entra ID', 'Identity governance', 'PIM', 'Conditional Access', 'Authentication flows'],
    array['Support enterprise identity programs', 'Improve governance controls', 'Troubleshoot access issues'],
    array['PIM', 'Authentication', 'Governance'],
    86,
    80,
    true
  ),
  (
    'https://jobs.example.com/infosys/azure-identity-administrator',
    'infosys-azure-identity-administrator-pune',
    'Infosys',
    'Azure Identity Administrator',
    'Cloud Operations',
    'Pune',
    'India',
    'onsite',
    'junior',
    1800000,
    2400000,
    'INR',
    '18-24 LPA',
    'Administer Azure identity services, automate group and user provisioning, and support MFA rollouts.',
    array['Azure AD', 'MFA', 'PowerShell', 'Graph API scripting'],
    array['Manage user access', 'Support MFA enablement', 'Create automation scripts'],
    array['Azure AD administration', 'Automation', 'Support scenarios'],
    82,
    78,
    true
  ),
  (
    'https://jobs.example.com/deloitte/cloud-iam-specialist',
    'deloitte-cloud-iam-specialist-hyderabad',
    'Deloitte',
    'Cloud IAM Specialist',
    'Cyber Identity',
    'Hyderabad',
    'India',
    'hybrid',
    'mid',
    2500000,
    3200000,
    'INR',
    '25-32 LPA',
    'Implement cloud IAM controls, privileged access programs, and identity compliance reporting.',
    array['Cloud IAM', 'PIM', 'Access certification', 'Identity compliance', 'Automation'],
    array['Implement access controls', 'Support certification campaigns', 'Document identity risks'],
    array['PIM', 'Compliance', 'Automation'],
    85,
    79,
    true
  )
on conflict (canonical_url) do update
set
  dedupe_key = excluded.dedupe_key,
  company = excluded.company,
  role_title = excluded.role_title,
  department = excluded.department,
  location = excluded.location,
  geography = excluded.geography,
  work_mode = excluded.work_mode,
  experience_level = excluded.experience_level,
  salary_min = excluded.salary_min,
  salary_max = excluded.salary_max,
  salary_currency = excluded.salary_currency,
  salary_range = excluded.salary_range,
  description_normalized = excluded.description_normalized,
  required_skills = excluded.required_skills,
  responsibilities = excluded.responsibilities,
  interview_topics = excluded.interview_topics,
  quality_score = excluded.quality_score,
  freshness_score = excluded.freshness_score,
  is_active = excluded.is_active,
  updated_at = now();
